---
title: 'Study 2: Data preparation'
output: pdf_document
  keep_md: true
---

This R markdown provides the data preparation for our CogSci proceedings paper (Jansen, Paxton, Krafft, Lombrozo, & Griffiths, *in preparation*).

**Code written by**: A. Paxton (University of California, Berkeley)

**Date last modified**: 31 January 2018

***

# Data import

***

## Preliminaries

```{r prep-prelim, warning = FALSE, error = FALSE, message = FALSE}

# clear our workspace
rm(list=ls())

# read in libraries and create functions
source('./supplementary-code/required_packages-sim.r')
source('./supplementary-code/libraries_and_functions-sim.r')

```

***

## Concatenate experiment files

```{r concatenate-data, warning = FALSE, error = FALSE, message = FALSE}

# get list of individual experiments included in the data
experiment_files = list.dirs('./data', recursive=FALSE)

# concatenate the files
vector_files = data.frame()
info_files = data.frame()
questionnaire_files = data.frame()
node_files = data.frame()
participant_files = data.frame()
for (experiment in experiment_files){
  
  # read in the next experiment's files and add ID to each
  exp_id = strsplit(as.character(experiment),"/|-")[[1]][3]
  
  # extract the metadata information
  code_version = str_extract(experiment,"code_version--\\d+") %>% str_extract(.,'\\d+') #lookbehind wasn't working, not sure why
  story_num = str_extract(experiment,"story_num--\\d+") %>% str_extract(.,'\\d+')
  rep = str_extract(experiment,"rep--\\d+") %>% str_extract(.,'\\d+')
  
  # read in vector file
  next_vector = read_csv(paste(experiment,'/vector.csv',sep='')) %>% 
    slice(-1) %>%
    mutate(experiment = exp_id) %>%
    mutate(code_version = code_version) %>%
    mutate(story_num = story_num) %>%
    mutate(rep = rep) %>%
    select(-contains('property'))
  
  # read in info
  next_info = read_csv(paste(experiment,'/info.csv',sep='')) %>% 
    slice(-1) %>%
    mutate(experiment = exp_id) %>%
    mutate(code_version = code_version) %>%
    mutate(story_num = story_num) %>%
    mutate(rep = rep) %>%
    select(-contains('property'))
  
  # read in questionnaire
  next_q = read_csv(paste(experiment,'/question.csv',sep='')) %>% 
    slice(-1) %>%
    mutate(experiment = exp_id) %>%
    mutate(code_version = code_version) %>%
    mutate(story_num = story_num) %>%
    mutate(rep = rep) %>%
    select(-contains('property'))
  
  # read in node information
  next_node = read_csv(paste(experiment,'/node.csv',sep='')) %>% 
    slice(-1) %>%
    mutate(experiment = exp_id) %>%
    mutate(code_version = code_version) %>%
    mutate(story_num = story_num) %>%
    mutate(rep = rep) %>%
    select(-contains('property'))
  
  # read in participant information
  next_participant = read_csv(paste(experiment,'/participant.csv',sep='')) %>% 
    slice(-1) %>%
    mutate(experiment = exp_id) %>%
    mutate(code_version = code_version) %>%
    mutate(story_num = story_num) %>%
    mutate(rep = rep) %>%
    select(-contains('property'))

  # append to group files
  vector_files = rbind.data.frame(vector_files, next_vector)
  info_files = rbind.data.frame(info_files, next_info)
  questionnaire_files = rbind.data.frame(questionnaire_files, next_q)
  node_files = rbind.data.frame(node_files, next_node)
  participant_files = rbind.data.frame(participant_files, next_participant)

}

```


